image: debian:testing-slim

before_script:
  # make aliases be usable from different jobs, see: https://gitlab.com/gitlab-org/gitlab-runner/issues/1083
  - shopt -s expand_aliases
  # alias dir Arduino CLI to always include custom config file
  - alias arduinocli="bin/arduino-cli --config-file $CI_PROJECT_DIR/preferences.txt"
  
# cache the Arduino CLI setup and config  
cache:
  paths:
    - preferences.txt
    - Arduino/**
    - .arduino15/**  
    - bin/**
  
install Arduino CLI:
  stage: .pre
  script:
    # install CURL command to be able to install Arduino CLI
    - ./setup-build-env.sh  

build DemoSketch:
  stage: build
  script:
    - ./build.sh examples/DemoSketch/DemoSketch.ino
    
build Communication_test:
  stage: build
  script:
    - ./build.sh examples/Communication_test/Communication_test.ino

build DemoSketch_without_pins:
  stage: build
  script:
    - ./build.sh examples/DemoSketch_without_pins/DemoSketch_without_pins.ino    
    