image: debian:testing-slim

before_script:
  - echo "doing before script ..."
  - echo "doing before script ... *DONE*"
  
# cache the Arduino CLI setup and config from .pre
cache:
  paths:
    - Arduino/**
    - .arduino15/**  
    - arduino-cli/**
  
install Arduino CLI:
  stage: .pre
  script:
    - ./setup-build-env.sh  

build DemoSketch:
  stage: build
  script:
    - ./build.sh examples/DemoSketch/DemoSketch.ino
    
build Communication_test:
  stage: build
  script:
    - ./build.sh examples/Communication_test/Communication_test.ino

build DemoSketch_without_pins:
  stage: build
  script:
    - ./build.sh examples/DemoSketch_without_pins/DemoSketch_without_pins.ino    
    