# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

before_script:
  - echo "sourcing arduino build from adafruit ..."
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - echo "sourcing arduino build from adafruit ... *DONE*"  

after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)  

install:
  stage: build
  script:
    - arduino --install-library "OneWire","DallasTemperature","SparkFun HTU21D Humidity and Temperature Sensor Breakout","FlashStorage","CRC32"
    
build:
  stage: build
  script:
#   - build_main_platforms
    - build_platform uno
    - build_platform leonardo
    - build_platform zero
#    - build_platform esp8266
